"""
MONEI API v1

The MONEI API is organized around REST principles. Our API is designed to be intuitive and developer-friendly.  ### Base URL  All API requests should be made to:  ``` https://api.monei.com/v1 ```  ### Environment  MONEI provides two environments:  - **Test Environment**: For development and testing without processing real payments - **Live Environment**: For processing real transactions in production  ### Client Libraries  We provide official SDKs to simplify integration:  - [PHP SDK](https://github.com/MONEI/monei-php-sdk) - [Python SDK](https://github.com/MONEI/monei-python-sdk) - [Node.js SDK](https://github.com/MONEI/monei-node-sdk) - [Postman Collection](https://postman.monei.com/)  Our SDKs handle authentication, error handling, and request formatting automatically.  You can download the OpenAPI specification from the https://js.monei.com/api/v1/openapi.json and generate your own client library using the [OpenAPI Generator](https://openapi-generator.tech/).  ### Important Requirements  - All API requests must be made over HTTPS - If you are not using our official SDKs, you **must provide a valid `User-Agent` header** with each request - Requests without proper authentication will return a `401 Unauthorized` error  ### Error Handling  The API returns consistent error codes and messages to help you troubleshoot issues. Each response includes a `statusCode` attribute indicating the outcome of your request.  ### Rate Limits  The API implements rate limiting to ensure stability. If you exceed the limits, requests will return a `429 Too Many Requests` status code.   # noqa: E501

The version of the OpenAPI document: 1.9.0
Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401

from Monei.api_client import ApiClient, Endpoint as _Endpoint
from Monei.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types,
)
from Monei.model.bad_request_error import BadRequestError
from Monei.model.internal_server_error import InternalServerError
from Monei.model.not_found_error import NotFoundError
from Monei.model.payment_methods import PaymentMethods
from Monei.model.service_unavailable_error import ServiceUnavailableError
from Monei.model.unauthorized_error import UnauthorizedError
from Monei.model.unprocessable_entity_error import UnprocessableEntityError


class PaymentMethodsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        self.get_endpoint = _Endpoint(
            settings={
                "response_type": (PaymentMethods,),
                "auth": ["APIKey"],
                "endpoint_path": "/payment-methods",
                "operation_id": "get",
                "http_method": "GET",
                "servers": None,
            },
            params_map={
                "all": [
                    "account_id",
                    "payment_id",
                    "amount",
                    "currency",
                    "country_code",
                ],
                "required": [],
                "nullable": [],
                "enum": [],
                "validation": [],
            },
            root_map={
                "validations": {},
                "allowed_values": {},
                "openapi_types": {
                    "account_id": (str,),
                    "payment_id": (str,),
                    "amount": (int,),
                    "currency": (str,),
                    "country_code": (str,),
                },
                "attribute_map": {
                    "account_id": "accountId",
                    "payment_id": "paymentId",
                    "amount": "amount",
                    "currency": "currency",
                    "country_code": "countryCode",
                },
                "location_map": {
                    "account_id": "query",
                    "payment_id": "query",
                    "amount": "query",
                    "currency": "query",
                    "country_code": "query",
                },
                "collection_format_map": {},
            },
            headers_map={
                "accept": ["application/json"],
                "content_type": [],
            },
            api_client=api_client,
        )
        self.get_allowed_endpoint = _Endpoint(
            settings={
                "response_type": (PaymentMethods,),
                "auth": ["APIKey"],
                "endpoint_path": "/allowed-payment-methods",
                "operation_id": "get_allowed",
                "http_method": "GET",
                "servers": None,
            },
            params_map={
                "all": [
                    "payment_id",
                    "amount",
                    "currency",
                    "country_code",
                ],
                "required": [],
                "nullable": [],
                "enum": [],
                "validation": [],
            },
            root_map={
                "validations": {},
                "allowed_values": {},
                "openapi_types": {
                    "payment_id": (str,),
                    "amount": (int,),
                    "currency": (str,),
                    "country_code": (str,),
                },
                "attribute_map": {
                    "payment_id": "paymentId",
                    "amount": "amount",
                    "currency": "currency",
                    "country_code": "countryCode",
                },
                "location_map": {
                    "payment_id": "query",
                    "amount": "query",
                    "currency": "query",
                    "country_code": "query",
                },
                "collection_format_map": {},
            },
            headers_map={
                "accept": ["application/json"],
                "content_type": [],
            },
            api_client=api_client,
        )
        self.get_client_endpoint = _Endpoint(
            settings={
                "response_type": (PaymentMethods,),
                "auth": [],
                "endpoint_path": "/client-payment-methods",
                "operation_id": "get_client",
                "http_method": "GET",
                "servers": None,
            },
            params_map={
                "all": [
                    "account_id",
                    "payment_id",
                    "amount",
                    "currency",
                    "country_code",
                ],
                "required": [],
                "nullable": [],
                "enum": [],
                "validation": [],
            },
            root_map={
                "validations": {},
                "allowed_values": {},
                "openapi_types": {
                    "account_id": (str,),
                    "payment_id": (str,),
                    "amount": (int,),
                    "currency": (str,),
                    "country_code": (str,),
                },
                "attribute_map": {
                    "account_id": "accountId",
                    "payment_id": "paymentId",
                    "amount": "amount",
                    "currency": "currency",
                    "country_code": "countryCode",
                },
                "location_map": {
                    "account_id": "query",
                    "payment_id": "query",
                    "amount": "query",
                    "currency": "query",
                    "country_code": "query",
                },
                "collection_format_map": {},
            },
            headers_map={
                "accept": ["application/json"],
                "content_type": [],
            },
            api_client=api_client,
        )

    def get(self, **kwargs):
        """Get Payment Methods  # noqa: E501

        **Deprecated.** Use [Get Allowed Payment Methods](#tag/Payment-Methods/operation/paymentMethods_getAllowed) for server-side (API key) or [Get Client Payment Methods](#tag/Payment-Methods/operation/paymentMethods_getClient) for client-side usage instead.  Retrieve available payment methods for an account or a specific payment.  You can provide either an `accountId` or a `paymentId` as a query parameter to get the available payment methods.  When providing a `paymentId`, the response will include additional payment-specific information such as amount and currency.  You can also filter results by `amount`, `currency`, or `countryCode` to narrow down available payment methods.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get(async_req=True)
        >>> result = thread.get()


        Keyword Args:
            account_id (str): The ID of the account to get payment methods for. [optional]
            payment_id (str): The ID of the payment to get payment methods for. [optional]
            amount (int): Amount in the smallest currency unit (e.g. cents). Used to filter payment methods by amount limits.. [optional]
            currency (str): Three-letter ISO 4217 currency code, in uppercase. Used to filter payment methods by currency support.. [optional]
            country_code (str): Two-letter ISO 3166-1 alpha-2 country code. Used to filter payment methods by country availability.. [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            PaymentMethods
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs["async_req"] = kwargs.get("async_req", False)
        kwargs["_return_http_data_only"] = kwargs.get("_return_http_data_only", True)
        kwargs["_preload_content"] = kwargs.get("_preload_content", True)
        kwargs["_request_timeout"] = kwargs.get("_request_timeout", None)
        kwargs["_check_input_type"] = kwargs.get("_check_input_type", True)
        kwargs["_check_return_type"] = kwargs.get("_check_return_type", True)
        kwargs["_spec_property_naming"] = kwargs.get("_spec_property_naming", False)
        kwargs["_content_type"] = kwargs.get("_content_type")
        kwargs["_host_index"] = kwargs.get("_host_index")
        kwargs["_request_auths"] = kwargs.get("_request_auths", None)
        return self.get_endpoint.call_with_http_info(**kwargs)

    def get_allowed(self, **kwargs):
        """Get Allowed Payment Methods  # noqa: E501

        Retrieve allowed payment methods for your account. Requires API key authentication.  The account is automatically determined from the API key — no `accountId` parameter is needed. Can be called with no parameters to get all available payment methods.  Optionally provide a `paymentId` to get payment methods for a specific transaction, or filter by `amount`, `currency`, or `countryCode`.  > **Note:** This endpoint does not auto-detect the customer's country. Pass `countryCode` explicitly if you need country-based filtering.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_allowed(async_req=True)
        >>> result = thread.get()


        Keyword Args:
            payment_id (str): The ID of the payment to get payment methods for. When provided, the response includes payment-specific information such as amount and currency.. [optional]
            amount (int): Amount in the smallest currency unit (e.g. cents). Used to filter payment methods by amount limits.. [optional]
            currency (str): Three-letter ISO 4217 currency code, in uppercase. Used to filter payment methods by currency support.. [optional]
            country_code (str): Two-letter ISO 3166-1 alpha-2 country code. Used to filter payment methods by country availability.. [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            PaymentMethods
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs["async_req"] = kwargs.get("async_req", False)
        kwargs["_return_http_data_only"] = kwargs.get("_return_http_data_only", True)
        kwargs["_preload_content"] = kwargs.get("_preload_content", True)
        kwargs["_request_timeout"] = kwargs.get("_request_timeout", None)
        kwargs["_check_input_type"] = kwargs.get("_check_input_type", True)
        kwargs["_check_return_type"] = kwargs.get("_check_return_type", True)
        kwargs["_spec_property_naming"] = kwargs.get("_spec_property_naming", False)
        kwargs["_content_type"] = kwargs.get("_content_type")
        kwargs["_host_index"] = kwargs.get("_host_index")
        kwargs["_request_auths"] = kwargs.get("_request_auths", None)
        return self.get_allowed_endpoint.call_with_http_info(**kwargs)

    def get_client(self, **kwargs):
        """Get Client Payment Methods  # noqa: E501

        Retrieve available payment methods from the client side. No authentication required.  You must provide either an `accountId` or a `paymentId` as a query parameter.  When providing a `paymentId`, the response includes payment-specific information such as amount and currency.  If `countryCode` is not provided, it is automatically detected from the client's IP address to filter payment methods by geographic availability.  You can also filter by `amount` or `currency`.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_client(async_req=True)
        >>> result = thread.get()


        Keyword Args:
            account_id (str): The ID of the account to get payment methods for. Either `accountId` or `paymentId` must be provided.. [optional]
            payment_id (str): The ID of the payment to get payment methods for. Either `accountId` or `paymentId` must be provided.. [optional]
            amount (int): Amount in the smallest currency unit (e.g. cents). Used to filter payment methods by amount limits.. [optional]
            currency (str): Three-letter ISO 4217 currency code, in uppercase. Used to filter payment methods by currency support.. [optional]
            country_code (str): Two-letter ISO 3166-1 alpha-2 country code. Used to filter payment methods by country availability. If not provided, the country is automatically detected from the client's IP address.. [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            PaymentMethods
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs["async_req"] = kwargs.get("async_req", False)
        kwargs["_return_http_data_only"] = kwargs.get("_return_http_data_only", True)
        kwargs["_preload_content"] = kwargs.get("_preload_content", True)
        kwargs["_request_timeout"] = kwargs.get("_request_timeout", None)
        kwargs["_check_input_type"] = kwargs.get("_check_input_type", True)
        kwargs["_check_return_type"] = kwargs.get("_check_return_type", True)
        kwargs["_spec_property_naming"] = kwargs.get("_spec_property_naming", False)
        kwargs["_content_type"] = kwargs.get("_content_type")
        kwargs["_host_index"] = kwargs.get("_host_index")
        kwargs["_request_auths"] = kwargs.get("_request_auths", None)
        return self.get_client_endpoint.call_with_http_info(**kwargs)
