# coding: utf-8

"""
    MONEI API v1

    <p>The MONEI API is organized around <a href=\"https://en.wikipedia.org/wiki/Representational_State_Transfer\">REST</a> principles. Our API is designed to be intuitive and developer-friendly.</p> <h3>Base URL</h3> <p>All API requests should be made to:</p> <pre><code>https://api.monei.com/v1 </code></pre> <h3>Environment</h3> <p>MONEI provides two environments:</p> <ul> <li><strong>Test Environment</strong>: For development and testing without processing real payments</li> <li><strong>Live Environment</strong>: For processing real transactions in production</li> </ul> <h3>Client Libraries</h3> <p>We provide official SDKs to simplify integration:</p> <ul> <li><a href=\"https://github.com/MONEI/monei-php-sdk\">PHP SDK</a></li> <li><a href=\"https://github.com/MONEI/monei-python-sdk\">Python SDK</a></li> <li><a href=\"https://github.com/MONEI/monei-node-sdk\">Node.js SDK</a></li> <li><a href=\"https://postman.monei.com/\">Postman Collection</a></li> </ul> <p>Our SDKs handle authentication, error handling, and request formatting automatically.</p> <h3>Important Requirements</h3> <ul> <li>All API requests must be made over HTTPS</li> <li>If you are not using our official SDKs, you <strong>must provide a valid <code>User-Agent</code> header</strong> with each request</li> <li>Requests without proper authentication will return a <code>401 Unauthorized</code> error</li> </ul> <h3>Error Handling</h3> <p>The API returns consistent error codes and messages to help you troubleshoot issues. Each response includes a <code>statusCode</code> attribute indicating the outcome of your request.</p> <p><a href=\"https://docs.monei.com/api/errors\">View complete list of status codes →</a></p> <h3>Rate Limits</h3> <p>The API implements rate limiting to ensure stability. If you exceed the limits, requests will return a <code>429 Too Many Requests</code> status code.</p>   # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from Monei.configuration import Configuration


class PaymentPaymentMethodCardInput(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'number': 'str',
        'cvc': 'str',
        'exp_month': 'str',
        'exp_year': 'str',
        'cardholder_name': 'str',
        'cardholder_email': 'str'
    }

    attribute_map = {
        'number': 'number',
        'cvc': 'cvc',
        'exp_month': 'expMonth',
        'exp_year': 'expYear',
        'cardholder_name': 'cardholderName',
        'cardholder_email': 'cardholderEmail'
    }

    def __init__(self, number=None, cvc=None, exp_month=None, exp_year=None, cardholder_name=None, cardholder_email=None, local_vars_configuration=None):  # noqa: E501
        """PaymentPaymentMethodCardInput - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._number = None
        self._cvc = None
        self._exp_month = None
        self._exp_year = None
        self._cardholder_name = None
        self._cardholder_email = None
        self.discriminator = None

        if number is not None:
            self.number = number
        if cvc is not None:
            self.cvc = cvc
        if exp_month is not None:
            self.exp_month = exp_month
        if exp_year is not None:
            self.exp_year = exp_year
        if cardholder_name is not None:
            self.cardholder_name = cardholder_name
        if cardholder_email is not None:
            self.cardholder_email = cardholder_email

    @property
    def number(self):
        """Gets the number of this PaymentPaymentMethodCardInput.  # noqa: E501

        The card number, as a string without any separators.  # noqa: E501

        :return: The number of this PaymentPaymentMethodCardInput.  # noqa: E501
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this PaymentPaymentMethodCardInput.

        The card number, as a string without any separators.  # noqa: E501

        :param number: The number of this PaymentPaymentMethodCardInput.  # noqa: E501
        :type: str
        """

        self._number = number

    @property
    def cvc(self):
        """Gets the cvc of this PaymentPaymentMethodCardInput.  # noqa: E501

        Card security code.  # noqa: E501

        :return: The cvc of this PaymentPaymentMethodCardInput.  # noqa: E501
        :rtype: str
        """
        return self._cvc

    @cvc.setter
    def cvc(self, cvc):
        """Sets the cvc of this PaymentPaymentMethodCardInput.

        Card security code.  # noqa: E501

        :param cvc: The cvc of this PaymentPaymentMethodCardInput.  # noqa: E501
        :type: str
        """

        self._cvc = cvc

    @property
    def exp_month(self):
        """Gets the exp_month of this PaymentPaymentMethodCardInput.  # noqa: E501

        Two-digit number representing the card's expiration month.  # noqa: E501

        :return: The exp_month of this PaymentPaymentMethodCardInput.  # noqa: E501
        :rtype: str
        """
        return self._exp_month

    @exp_month.setter
    def exp_month(self, exp_month):
        """Sets the exp_month of this PaymentPaymentMethodCardInput.

        Two-digit number representing the card's expiration month.  # noqa: E501

        :param exp_month: The exp_month of this PaymentPaymentMethodCardInput.  # noqa: E501
        :type: str
        """

        self._exp_month = exp_month

    @property
    def exp_year(self):
        """Gets the exp_year of this PaymentPaymentMethodCardInput.  # noqa: E501

        Two-digit number representing the card's expiration year.  # noqa: E501

        :return: The exp_year of this PaymentPaymentMethodCardInput.  # noqa: E501
        :rtype: str
        """
        return self._exp_year

    @exp_year.setter
    def exp_year(self, exp_year):
        """Sets the exp_year of this PaymentPaymentMethodCardInput.

        Two-digit number representing the card's expiration year.  # noqa: E501

        :param exp_year: The exp_year of this PaymentPaymentMethodCardInput.  # noqa: E501
        :type: str
        """

        self._exp_year = exp_year

    @property
    def cardholder_name(self):
        """Gets the cardholder_name of this PaymentPaymentMethodCardInput.  # noqa: E501

        The cardholder's name, as stated in the credit card.  # noqa: E501

        :return: The cardholder_name of this PaymentPaymentMethodCardInput.  # noqa: E501
        :rtype: str
        """
        return self._cardholder_name

    @cardholder_name.setter
    def cardholder_name(self, cardholder_name):
        """Sets the cardholder_name of this PaymentPaymentMethodCardInput.

        The cardholder's name, as stated in the credit card.  # noqa: E501

        :param cardholder_name: The cardholder_name of this PaymentPaymentMethodCardInput.  # noqa: E501
        :type: str
        """

        self._cardholder_name = cardholder_name

    @property
    def cardholder_email(self):
        """Gets the cardholder_email of this PaymentPaymentMethodCardInput.  # noqa: E501

        The cardholder's email address.  # noqa: E501

        :return: The cardholder_email of this PaymentPaymentMethodCardInput.  # noqa: E501
        :rtype: str
        """
        return self._cardholder_email

    @cardholder_email.setter
    def cardholder_email(self, cardholder_email):
        """Sets the cardholder_email of this PaymentPaymentMethodCardInput.

        The cardholder's email address.  # noqa: E501

        :param cardholder_email: The cardholder_email of this PaymentPaymentMethodCardInput.  # noqa: E501
        :type: str
        """

        self._cardholder_email = cardholder_email

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaymentPaymentMethodCardInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PaymentPaymentMethodCardInput):
            return True

        return self.to_dict() != other.to_dict()
